### ISSUE TITLE
[BUG] Can't start alpha3

### ISSUE THREAD

**Issue by andre-dierker** [H-PixelDroid/PixelDroid#233]
* [x] I checked the release notes for known issues
* [x] I checked the existing issues
* [x] I checked that the issue is not related to my instance configuration, and that my instance has the latest version of pixelfed

Describe step by step how to reproduce the bug, include screenshots if possible.  
I can't start the new Alpha3 version. What I've done so far:
- Just install alpha3 over alpha2
- Delete alpha2, then install alpha3
- Wipe data, then delete alpha2, then install alpha3
- Data folders are removed every time
- installing alpha2 works fine

Enviroment:
Xiaomi Mi8
MIUI 11.04
Android 10
Lates security patches 01.04.2020

Trace produced by my phone:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.h.pixeldroid/com.h.pixeldroid.MainActivity}: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3304)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
	at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:154)
	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:135)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:142)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:428)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
	at com.h.pixeldroid.db.UserDao_Impl.getActiveUser(UserDao_Impl.java:204)
	at com.h.pixeldroid.MainActivity.onCreate(MainActivity.kt:62)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Activity.performCreate(Activity.java:7880)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
	... 11 more
```

**Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.**
For this, [stackoverflow](https://stackoverflow.com/questions/44197309/room-cannot-verify-the-data-integrity/44197403) suggests, that it is possible that the android auto backup is restoring the old database on install.

Thank you for your nice work.
André

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
I also saw that stackoverflow post. I don't have a phone with Google Play Services so it's hard to take a look at the backups.

Is there a way to delete backups? I don't even know what the UI of that looks like

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
We can disable backups actually, I don't think there's any reason to keep them anyways since I don't think there are ways other than through Google Play to do them :thinking:
